Fixing missing PG-13 results
PolyMeilex/node-myanimelist pull request #34
Opened 2022-10-12 16:56 UTC by haruajsuru

For some reason MAL flaged some PG-13 result as nsfw and those result won't show up in search without snfw = true parameter

I set nsfw default to true to make sure all the api return all search results correct

this is just a quick fix I put together on github if anyone want to reformat it or have better ideal, feel free to contribute your code

2022-10-12 17:11 UTC, PolyMeilex requested changes
Thank you, sounds good.

If merged, this closes https://github.com/PolyMeilex/node-myanimelist/pull/33 and #32 right?

2022-10-12 17:11 UTC, PolyMeilex commented on src/methods/malApi/anime/index.ts
> +    nsfw? : boolean | true
What does `boolean | true` mean? I would expect `boolean` type to already include `true` case.

2022-10-12 17:11 UTC, PolyMeilex commented on src/methods/malApi/anime/index.ts
> +    config.params.nsfw = nsfw;
Would be good to do null/undefined check, or include a default value in case `nsfw` arg is null or undefined.

2022-10-14 07:20 UTC, haruajsuru commented
updated code properly this time and confirm all search results return correctly, I didn't have opportunity to check other functions (ranking, seasonal) so I will leave them alone for now

Also I think that in our doc/example codes should have warning about the nsfw parameter to make sure that people will know beforehand about the missing results problem

2022-10-18 16:16 UTC, merged